/*
 * This source file was generated by the Gradle 'init' task
 */
package _GradleDemo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

class LibraryTest {
    @Test void testHelloWorld() {
    	ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        Library.main(null);

        String expectedOutput = "hello world";
        String input = outContent.toString().toLowerCase();
        if(input.indexOf(expectedOutput) != -1) {
        	input = "hello world";
        }

        assertEquals(expectedOutput,input);
    }
    @Test void testHelloZebrack() {
    	ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        Library.main(null);

        String expectedOutput = "zebrack";
        String input = outContent.toString().toLowerCase();
        
        String found = input;
        if(input.indexOf(expectedOutput) != -1) {
        	found = "zebrack";
        }
        assertEquals(expectedOutput,found);
        
        expectedOutput = "happy";
        found = input;
        if(input.indexOf(expectedOutput) != -1) {
        	found = "happy";
        }
        assertEquals(expectedOutput,found);
        
        
        expectedOutput = "birthday";
        found = input;
        if(input.indexOf(expectedOutput) != -1) {
        	found = "birthday";
        }
        assertEquals(expectedOutput,found);
        
    }
    @Test void testTen() {
    	ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        Library.main(null);

        String expectedOutput = "10";
        String input = outContent.toString().toLowerCase();
        if(input.indexOf(expectedOutput) != -1) {
        	input = "10";
        }

        assertEquals(expectedOutput,input);
    }
}
