/*
 * This source file was generated by the Gradle 'init' task
 */
package _GradleDemo;

public class Library {
	public static void main(String[] args) {
		//Print out hello world (5 points)
		
		//Wish Mr. Zebrack a happy birthday (15 points)
		System.out.println("happy birthday mr. Zebrack");		
		//print out the result from 5 + 5; (20 points)
		
	}
}
